# Replace with your Discord Application ID
application_id: "1311204057490259979"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 3

# Activity Details
name: "Marewa"
details: "Be kind"
state: "Join our discord"

# Activity Images
largeImageKey: "1463536328313536553"
largeImageText: "Marewa"
smallImageKey: "1463536162122764298"
smallImageText: "Subscribe"

# Activity URL (optional, works only with certain types)
url: "https://discord.gg/BTScNHDV4D"

# Activity Buttons (optional)
# buttons:
#   - name: "Visit Website"
#     url: "https://www.nexoscreator.tech"
#   - name: "GitHub Repo"
#     url: "https://github.com/nexoslabs/discord-24-7-rich-presence"

# Activity Custom status
custom_status: "Watching Marewa"
custom_emoji: "🔥"
